### ISSUE TITLE
Document usage of Ansible Tower instead of AWX

### ISSUE THREAD

**Issue by clerixmaxime** [nmasse-itix/rhte-api#4]
FYI the documentation to use Ansible Tower instead of AWX

### 13/ Deploy Ansible Tower

Documentation : https://docs.ansible.com/ansible-tower/latest/html/administration/openshift_configuration.html
#### Create a PVC for PostgreSQL

```sh
oc project tower
oc apply -f - <<EOF
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "postgresql"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
EOF
```

#### Create a virtual Env
This demonstration requires at least Jinja 2.8 to be run (Currently Ansible Tower 3.4 uses Jinja 2.7.2). Before deploying Ansible Tower, we have to create a virtual env in order to run our playbooks.

Create a Dockerfile with the following content :
```Dockerfile
FROM registry.access.redhat.com/ansible-tower-34/ansible-tower:latest
USER root
RUN yum install -y gcc
RUN mkdir -p /var/lib/awx/venv/jinja2.8
RUN virtualenv --system-site-packages /var/lib/awx/venv/jinja2.8
RUN sh -c ". /var/lib/awx/venv/jinja2.8/bin/activate ; /var/lib/awx/venv/jinja2.8/bin/pip install python-memcached psutil ; pip install --upgrade jinja2;"
```

Build and push the Docker image. Make sure you replace the name of the docker image with your own one. https://quay.io is a great public registry to host your custom Ansible images.
```
docker build -t quay.io/mclerix/ansible-tower-venv-jinja28:jinja2.10 .
docker push quay.io/mclerix/ansible-tower-venv-jinja28:jinja2.10
```

Now that your Ansible Virtual Env is ready, we will deploy Ansible Tower based on this one.

#### Deploy Ansible Tower
Get Ansible Tower assets here as tar.gz : https://releases.ansible.com/ansible-tower/setup_openshift/?extIdCarryOver=true&sc_cid=701f2000001OH7YAAW

Download and extract the release that you want to deploy.

Modify the provided inventory file to match with your environment. You can change tower default credentials, postgreSQL and RabbitMQ configuration. The important section is Deploy into OpenShift. Replace the following value:

```yaml
openshift_host=https://<your_hostname>:8443
openshift_skip_tls_verify=true
openshift_project=tower
openshift_user=<your_username>
openshift_password=<your_password>
```

Then modify your inventory file in order to use the image that you build with a venv. Edit the file group_vars/all with the following value:
```yaml
[...]

kubernetes_web_image: quay.io/mclerix/ansible-tower-venv-jinja28
kubernetes_task_image: quay.io/mclerix/ansible-tower-venv-jinja28

[...]

kubernetes_task_version: 'jinja2.10'
kubernetes_web_version: 'jinja2.10'
```

Deploy into OpenShift : 
```sh
./setup_openshift.sh -- -v
```

If you don't want to store your OpenShift password in the inventory file, you can add it at launch with the following command:
```sh
./setup_openshift.sh -e openshift_password=<your_password> -- -v
```

### 14/ Configure project and job in Ansible Tower

Login on Ansible Tower as admin, go to the *Projects* section and add a new project with following properties :

* Name: `Deploy API to 3scale`
* Description: `Enable continuous deployment of an API to 3scale AMP`
* Organization: `default`
* SCM Type: `Git`
* SCM URL: `https://github.com/nmasse-itix/threescale-cicd-awx`
* SCM Branch/Tag/Commit: `master`

You can also tick `Update Revision on Launch` and setup a cache timeout.

Then you have to add a new *Job Template* with following properties :

* Name: `Deploy an API to 3scale`
* Project: `Deploy API to 3scale`
* Playbook: `deploy-api.yml`
* Inventory: `Prompt on Launch`
* Extra-variables: `Prompt on Launch`
* Ansible-Environment (allows to use the venv created before) : `/var/lib/awx/venv/jinja2.8`

For both the TEST and PROD environments, you will have to declare an inventory into AWX.

* Create an inventory named `3scale-test` and set the `Variables` field to:

```yaml
---
ansible_connection: local
```

* Save
* Move to the `Groups` section and create a group named `threescale`
* Set the `Variables` field to:

```yaml
---
threescale_cicd_access_token: <3scale_access_token>
threescale_cicd_api_environment_name: test
threescale_cicd_wildcard_domain: test.mc-apps.openhybridcloud.io
```

* Do not forget to replace the `threescale_cicd_access_token`, `threescale_cicd_api_environment_name` and `threescale_cicd_wildcard_domain` variables with respectively your access token to 3scale API Management backend, the name of environment as well as the wildcard that will be used to serve Gateway through Route.

* Move to the `Hosts` section
* Add a host that matches your 3scale Admin Portal (`<TENANT>-admin.3scale.net`). For example: `nmasse-redhat-admin.3scale.net`

* Duplicate this inventory and change the `threescale` group variables to:

```yaml
---
threescale_cicd_access_token: <3scale_access_token>
threescale_cicd_api_environment_name: prod
threescale_cicd_wildcard_domain: prod.mc-apps.openhybridcloud.io
```

* Change the name of the new inventory to `3scale-prod` and save
